### ISSUE TITLE
ArgumentError caused by encoding of commit message

### ISSUE THREAD

**Issue by bgeuken** [bkuhlmann/git-cop#39]
In one of my branches I was getting an ArgumentError when running ' git-cop --police'. I was able to workaround this by changing the environement variable via LANG=en_US.UTF-8.

git-cop version: 1.7.1
ruby version: 2.5.0

```bash
 git-cop --police
Traceback (most recent call last):
	19: from /usr/bin/git-cop:23:in `<main>'
	18: from /usr/bin/git-cop:23:in `load'
	17: from /usr/lib64/ruby/gems/2.5.0/gems/git-cop-1.7.1/bin/git-cop:9:in `<top (required)>'
	16: from /usr/lib64/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	15: from /usr/lib64/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	14: from /usr/lib64/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	13: from /usr/lib64/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	12: from /usr/lib64/ruby/gems/2.5.0/gems/git-cop-1.7.1/lib/git/cop/cli.rb:61:in `police'
	11: from /usr/lib64/ruby/gems/2.5.0/gems/git-cop-1.7.1/lib/git/cop/cli.rb:105:in `analyze_commits'
	10: from /usr/lib64/ruby/gems/2.5.0/gems/git-cop-1.7.1/lib/git/cop/cli.rb:101:in `load_collector'
	 9: from /usr/lib64/ruby/gems/2.5.0/gems/git-cop-1.7.1/lib/git/cop/runner.rb:12:in `run'
	 8: from /usr/lib64/ruby/gems/2.5.0/gems/git-cop-1.7.1/lib/git/cop/runner.rb:12:in `map'
	 7: from /usr/lib64/ruby/gems/2.5.0/gems/git-cop-1.7.1/lib/git/cop/runner.rb:12:in `block in run'
	 6: from /usr/lib64/ruby/gems/2.5.0/gems/git-cop-1.7.1/lib/git/cop/runner.rb:28:in `check'
	 5: from /usr/lib64/ruby/gems/2.5.0/gems/git-cop-1.7.1/lib/git/cop/runner.rb:28:in `map'
	 4: from /usr/lib64/ruby/gems/2.5.0/gems/git-cop-1.7.1/lib/git/cop/runner.rb:28:in `block in check'
	 3: from /usr/lib64/ruby/gems/2.5.0/gems/git-cop-1.7.1/lib/git/cop/collector.rb:15:in `add'
	 2: from /usr/lib64/ruby/gems/2.5.0/gems/git-cop-1.7.1/lib/git/cop/commits/saved.rb:42:in `hash'
	 1: from /usr/lib64/ruby/gems/2.5.0/gems/git-cop-1.7.1/lib/git/cop/commits/saved.rb:71:in `method_missing'
/usr/lib64/ruby/gems/2.5.0/gems/git-cop-1.7.1/lib/git/cop/commits/saved.rb:71:in `[]': invalid byte sequence in US-ASCII (ArgumentError)
```

**Comment by bkuhlmann** [comment]
Thanks, that's interesting. Will fix.
